### ISSUE TITLE
Crash with Hallowed Mana Flask on the ground

### ISSUE THREAD

**Issue by operinko** [TehCheat/PoEHUD#11]
As the title states, PoEHUD crashes when entering an area with a Hallowed Mana Flask on the ground, or if a Hallowed Mana Flask is dropped.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at PoeHUD.Hud.Loot.PoeFilterVisitor.VisitMain(MainContext context)
   at PoeFilterParser.Model.PoeFilterParser.MainContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at PoeHUD.Hud.Loot.ItemAlertPlugin.OnEntityAdded(EntityWrapper entity)
   at System.Action`1.Invoke(T obj)
   at PoeHUD.Models.EntityListWrapper.RefreshState()
   at PoeHUD.Controllers.GameController.RefreshState()
   at PoeHUD.Hud.ExternalOverlay.OnRender()
   at PoeHUD.Framework.Helpers.ActionHelper.SafeInvoke(Action action)
   at PoeHUD.Hud.UI.Graphics.RenderLoop()
   at PoeHUD.Hud.ExternalOverlay.<OnLoad>b__14_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoeHUD.Hud.ExternalOverlay.<OnLoad>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PoeHUD
    Assembly Version: 6.3.9600.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///E:/Train/poe/vmv-PoeHud-master/FY2iN.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Tools
    Assembly Version: 0.0.0.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///E:/Train/poe/vmv-PoeHud-master/FY2iN.exe
----------------------------------------
SharpDX.Desktop
    Assembly Version: 3.0.0.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///E:/Train/poe/vmv-PoeHud-master/FY2iN.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
FSharp.Core
    Assembly Version: 4.4.0.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///E:/Train/poe/vmv-PoeHud-master/FY2iN.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///E:/Train/poe/vmv-PoeHud-master/FY2iN.exe
----------------------------------------
SharpDX.Mathematics
    Assembly Version: 3.0.0.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///E:/Train/poe/vmv-PoeHud-master/FY2iN.exe
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
SharpDX
    Assembly Version: 3.0.0.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///E:/Train/poe/vmv-PoeHud-master/FY2iN.exe
----------------------------------------
SharpDX.Direct3D9
    Assembly Version: 3.0.0.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///E:/Train/poe/vmv-PoeHud-master/FY2iN.exe
----------------------------------------
System.Threading
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll
----------------------------------------
System.Collections
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.dll
----------------------------------------
PoeFilterParser
    Assembly Version: 1.0.0.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///E:/Train/poe/vmv-PoeHud-master/FY2iN.exe
----------------------------------------
Antlr4.Runtime
    Assembly Version: 4.5.0.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///E:/Train/poe/vmv-PoeHud-master/FY2iN.exe
----------------------------------------
System.Globalization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Globalization/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Globalization.dll
----------------------------------------
System.Reflection
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Reflection/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by Kronix420** [comment]
same problem. Worked perfectly through normal and cruel, but has been unusable in merciless.

**Comment by TehCheat** [comment]
In the short term, don't use the item filter part of the item alerter.  I haven't had a chance to look at the item filter part yet, but it's stable (at least for me) not using the item filter part.

**Comment by TehCheat** [comment]
Made a null reference check which prevents the null reference exception from catching.
