### ISSUE TITLE
Unhandled Exception 

### ISSUE THREAD

**Issue by den11111** [TehCheat/PoEHUD#252]
Since the last version (commit 8648645) i get the following unhandled exception error:

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'PoeFilterParser, Version=1.0.19.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'PoeFilterParser, Version=1.0.19.0, Culture=neutral, PublicKeyToken=null'
   at PoeHUD.Hud.Loot.ItemAlertPlugin.PoeFilterInit(String path)
   at PoeHUD.Hud.Loot.ItemAlertPlugin..ctor(GameController gameController, Graphics graphics, ItemAlertSettings settings, SettingsHub settingsHub)
   at PoeHUD.Hud.ExternalOverlay.<OnLoad>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

PoEHUD fails to load after this.
Previous commit everything ran fine.

**Comment by TehCheat** [comment]
Looks like you deleted a filter that it was pointing to, but that's just a guess.
