### ISSUE TITLE
Does not run on clean Windows 10 1803 installation

### ISSUE THREAD

**Issue by makhotkin** [TehCheat/PoEHUD#289]
Got a fresh system with win10 version 1803. PoE has launched without issues, yet the HUD won't start.
At first it was due to missing d9d_43.dll (fixed by installing DirectX End-User Runtime), but the second issue made me stuck.

Unable to load DLL 'cimgui': The specified module could not be found. Exception from HResult: 0x8007007E

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.DllNotFoundException: Unable to load DLL 'cimgui': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ImGuiNET.ImGuiNative.igGetIO()
   at ImGuiNET.ImGui..cctor()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
PoeHUD
    Assembly Version: 1.0.6736.41680
    Win32 Version: 1.0.*
    CodeBase: file:///C:/Games/PoEHUD-x64/HUee0pqZD.exe
----------------------------------------
SharpDX.Desktop
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///C:/Games/PoEHUD-x64/SharpDX.Desktop.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
SharpDX.Mathematics
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///C:/Games/PoEHUD-x64/SharpDX.Mathematics.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
ImGui.NET
    Assembly Version: 0.4.0.0
    Win32 Version: 0.4.0
    CodeBase: file:///C:/Games/PoEHUD-x64/ImGui.NET.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
SharpDX
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///C:/Games/PoEHUD-x64/SharpDX.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.3.21018
    CodeBase: file:///C:/Games/PoEHUD-x64/Newtonsoft.Json.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
SharpDX.Direct3D9
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///C:/Games/PoEHUD-x64/SharpDX.Direct3D9.DLL
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.3.0
    Win32 Version: 4.6.25519.03
    CodeBase: file:///C:/Games/PoEHUD-x64/System.Numerics.Vectors.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by TehCheat** [comment]
From the first page in the OwnedCore thread:


Requirements

Visual C 2015 Redistributable.
