### ISSUE TITLE
Problem(((

### ISSUE THREAD

**Issue by FalurFa** [TehCheat/PoEHUD#299]
Hello, I run the program and gets out here is a window:
08.07.2018 22:23 Program exited with message:
 System.TypeLoadException: Could not load type 'System.Numerics.Vector2' from assembly 'System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at PoeHUD.Controllers.GameController.get_UseGameStateController()
   at PoeHUD.Poe.RemoteMemoryObjects.TheGame.get_IngameStateReal()
   at PoeHUD.Poe.RemoteMemoryObjects.TheGame.get_IngameState()
   at PoeHUD.Controllers.StashTabController.CheckCacheStashTabs()
   at PoeHUD.Controllers.StashTabController..ctor()
   at PoeHUD.Controllers.GameController..ctor(Memory memory)
   at PoeHUD.Program.Main(String[] args)
Please, help me

**Comment by TehCheat** [comment]
Install the requirements. They're required.

**Comment by FalurFa** [comment]
Installed the new Framework and everything worked, thanks!
