### ISSUE TITLE
Can't load PoEHUD since 3.4.3.e update

### ISSUE THREAD

**Issue by KrazeSyche** [TehCheat/PoEHUD#318]
error is as follows
9/27/2018 6:06 PM Program exited with message:
 System.NullReferenceException: Object reference not set to an instance of an object.
   at PoeHUD.Framework.Memory.ReadStructsArray[T](Int64 startAddress, Int64 endAddress, Int32 structSize, Int32 maxCountLimit)
   at PoeHUD.Poe.RemoteMemoryObjects.ServerData.GetStashTabs(Int32 offsetBegin, Int32 offsetEnd)
   at PoeHUD.Controllers.StashTabController.CheckCacheStashTabs()
   at PoeHUD.Controllers.StashTabController..ctor()
   at PoeHUD.Controllers.GameController..ctor(Memory memory)
   at PoeHUD.Program.Main(String[] args)

**Comment by TSM-EVO** [comment]
Fresh install gives me the same error.

**Comment by TehCheat** [comment]
That's a broken plugin. Remove all of your plugins and see if it works. After you verify that HUD with no plugins works, add them back in one at a time. I think Stashie is the one causing this error, and hasn't been updated.
