### ISSUE TITLE
Show DPS

### ISSUE THREAD

**Issue by nartaki** [TehCheat/PoEHUD#345]
When i try to use it it crashes hud after a few seconds
`
************** Exception Text **************
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PoeHUD.Hud.Dps.DpsMeterPlugin.CalculateDps(Int32& aoeDamage, Int32& singleDamage)
   at PoeHUD.Hud.Dps.DpsMeterPlugin.Render()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PoeHUD.Framework.Helpers.ActionHelper.SafeInvoke(Action action)
   at PoeHUD.Hud.UI.Graphics.TryRender()
   at PoeHUD.Framework.Helpers.ActionHelper.SafeInvoke(Action action)
   at PoeHUD.Controllers.GameController.WhileLoop()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoeHUD.Hud.ExternalOverlay.<OnLoad>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
`

**Comment by Stridemann** [comment]
I pushed code fix for that, maybe someone will rebuild exe later.

**Comment by nartaki** [comment]
//closed
