### ISSUE TITLE
Some sort of error I'm getting

### ISSUE THREAD

**Issue by Yuskia** [TehCheat/PoEHUD#4]
Here's the error I'm getting, maybe you can help me out?

> 3/17/2016 8:22 PM Program exited with message:
>  System.Exception: Error when loading alert.wav| Please be sure a sound file exists at the specified location.: ---> System.IO.FileNotFoundException: Please be sure a sound file exists at the specified location.
>    at System.Media.SoundPlayer.Load()
>    at PoeHUD.Hud.Sounds.AddSound(String name)
>    --- End of inner exception stack trace ---
>    at PoeHUD.Hud.Sounds.AddSound(String name)
>    at PoeHUD.Hud.Sounds.LoadSounds()
>    at PoeHUD.Program.Main(String[] args)
> ------------------------------
> 3/17/2016 8:22 PM Program exited with message:
>  System.Exception: Error when loading alert.wav| Please be sure a sound file exists at the specified location.: ---> System.IO.FileNotFoundException: Please be sure a sound file exists at the specified location.
>    at System.Media.SoundPlayer.Load()
>    at PoeHUD.Hud.Sounds.AddSound(String name)
>    --- End of inner exception stack trace ---
>    at PoeHUD.Hud.Sounds.AddSound(String name)
>    at PoeHUD.Hud.Sounds.LoadSounds()
>    at PoeHUD.Program.Main(String[] args)
> ------------------------------

**Comment by Yuskia** [comment]
Here's a picture of the error as well, if it helps.

http://i.imgur.com/soULQBU.png

**Comment by Yuskia** [comment]
As it turns down I'm retarded and forgot that I removed the folder so I was only downloading a single file.
