### ISSUE TITLE
Program exited with message ~

### ISSUE THREAD

**Issue by Nikko89511** [TehCheat/PoEHUD#44]
Searched the Issues so far, nothing showed up. Getting this error as soon as i try to launch the executable or batch. Playing on steam. Will try normal game when its done updating. Maybe its something else though, so i will leave this here. Any help is greatly appreciated! 

```
---------------------------

---------------------------
Program exited with message:
 System.BadImageFormatException: Could not load file or assembly 'System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The module was expected to contain an assembly manifest.

File name: 'System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

   at Newtonsoft.Json.Converters.BinaryConverter.CanConvert(Type objectType)

   at Newtonsoft.Json.JsonSerializer.GetMatchingConverter(IList`1 converters, Type objectType)

   at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)

   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)

   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)

   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)

   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)

   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)

   at PoeHUD.Hud.Settings.SettingsHub.Save(SettingsHub settings)

   at PoeHUD.Hud.Settings.SettingsHub.Load()

   at PoeHUD.Hud.ExternalOverlay..ctor(GameController gameController, Func`1 gameEnded)

   at PoeHUD.Program.Main(String[] args)

---------------------------
OK   
---------------------------

```

**Comment by TehCheat** [comment]
Did you build this yourself?

**Comment by Nikko89511** [comment]
I downloaded it and ran it as is... is that wrong? Lol... i'm new to git and basically have 0 programming experience other than making some lame java calculator. Sorry if that was all wrong. :/

**Comment by TehCheat** [comment]
Nope, you did nothing wrong, just trying to figure out why the problem is occurring for you and nobody else (that I know of).  If you had built it yourself, I would assume you have the wrong version of the Newtonsoft.Json package on one of the projects.  Try downloading/installing the .NET 4.5 framework, that's usually the problem, though I don't see anything in the error that makes me think that's what it is.

**Comment by Nikko89511** [comment]
I tried installing it beforehand, but the installer said this version or a newer one is already installed. So I went ahead, downloaded the zip and tried running it. Then that error pops up. I will try to run it on the normal version of PoE (non-steam). I will report back then. I hope that is the issue. (I'm on win7 Ultimate x64 by the way, if that is of any help). Thanks for the quick replies! I really appreciate it!

**Comment by TehCheat** [comment]
When you downloaded HUD did you extract the Config, Sounds, and Textures folders as well?  If those are missing, you might get this error, I suppose.  Also if HUD was placed in a folder with restrictions (such as program files) it might not be able to access the settings file.  Just throwing stuff out there, as I haven't seen this issue before.

**Comment by Nikko89511** [comment]
I downloaded the zip, the new executable that was recompiled (although I got the error with the one in the zip and the newer one aswell), extracted the zip into my D: folder (system is on C: so D: is not restricted). 

This is what my folder looks like: http://prntscr.com/cko1kx

**Comment by Nikko89511** [comment]
I reinstalled my net framework and now am getting a new error, an unhandled exception. 

```
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at PoeHUD.Hud.ExternalOverlay.<OnLoad>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PoeHUD
    Assembly Version: 6.3.9600.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///D:/PoEHUD-2.4.0f/60rkA.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Tools
    Assembly Version: 0.0.0.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///D:/PoEHUD-2.4.0f/60rkA.exe
----------------------------------------
SharpDX.Desktop
    Assembly Version: 3.0.2.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///D:/PoEHUD-2.4.0f/60rkA.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
FSharp.Core
    Assembly Version: 4.4.0.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///D:/PoEHUD-2.4.0f/60rkA.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///D:/PoEHUD-2.4.0f/60rkA.exe
----------------------------------------
SharpDX.Mathematics
    Assembly Version: 3.0.2.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///D:/PoEHUD-2.4.0f/60rkA.exe
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
SharpDX
    Assembly Version: 3.0.2.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///D:/PoEHUD-2.4.0f/60rkA.exe
----------------------------------------
SharpDX.Direct3D9
    Assembly Version: 3.0.2.0
    Win32 Version: 6.3.9600.0
    CodeBase: file:///D:/PoEHUD-2.4.0f/60rkA.exe
----------------------------------------
System.Threading
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll
----------------------------------------
System.Collections
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

**Comment by Nikko89511** [comment]
Alright got it to work. Removed everything and did a re-download. Seems to have fixed it (I get a small ingame overlay).
